export const Projects = [
  {
    id: "1",
    plan: "FREE PLAN",
    date: "28-7-2025",
    name: "Home Decoration Toy",
    desc: "Help businesses to clearly ",
    fav_count: "14",
  },
  {
    id: "2",
    plan: "BRAND PLAN",
    date: "28-7-2025",
    name: "Express Laundromat",
    desc: "Help businesses to clearly define their annual e-commerce digital strategy by creating a high-level plan.",
    fav_count: "14",
  },
  {
    id: "3",
    plan: "FREE PLAN",
    date: "28-7-2025",
    name: "Asian Kitchen Restaurant",
    desc: "Help businesses to clearly define their annual e-commerce digital strategy by creating a high-level plan.",
    fav_count: "14",
  },
  {
    id: "4",
    plan: "FREE PLAN",
    date: "28-7-2025",
    name: "Online Training Program",
    desc: "Help businesses to clearly define their annual e-commerce digital strategy by creating a high-level plan.",
    fav_count: "14",
  },
  {
    id: "5",
    plan: "FREE PLAN",
    date: "28-7-2025",
    name: "Asian Kitchen Restaurant",
    desc: "Help businesses to clearly define their annual e-commerce digital strategy by creating a high-level plan. Help businesses to clearly define their annual e-commerce digital strategy by creating a high-level plan.",
    fav_count: "14",
  },
  {
    id: "6",
    plan: "FREE PLAN",
    date: "28-7-2025",
    name: "Online Training Program",
    desc: "Help businesses to clearly define their annual e-commerce digital strategy by creating a high-level plan.",
    fav_count: "14",
  },
];
